version: '3'
services:
  app:
    container_name: searcher_app
    build: .
    working_dir: /app
    tty: true
    env_file: dev.env
    ports:
      - "6666:6666"
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - default
      - flight_search_microservices

  db:
    container_name: searvher_db
    image: mongo:5.0.6
    env_file: dev.env
    volumes:
      - mongodb-data:/data/db


volumes:
  mongodb-data:


networks:
  flight_search_microservices:
    external:
      name: flight_search_microservices